from src.enums import aq_keys, measurements, rv_keys, keys

aq_measurements = {
    aq_keys['time']: measurements['interval'],
    aq_keys['us_aqi (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_pm2_5 (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_pm10 (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_nitrogen_dioxide (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_carbon_monoxide (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_ozone (USAQI)']: measurements['ordinal'],
    aq_keys['us_aqi_sulphur_dioxide (USAQI)']: measurements['ordinal'],
    aq_keys['methane (μg/m³)']: measurements['ratio'],
    aq_keys['uv_index_clear_sky ()']: measurements['ratio'],
    aq_keys['uv_index ()']: measurements['ratio'],
    aq_keys['dust (μg/m³)']: measurements['ratio'],
    aq_keys['aerosol_optical_depth ()']: measurements['ratio'],
    aq_keys['ozone (μg/m³)']: measurements['ratio'],
    aq_keys['sulphur_dioxide (μg/m³)']: measurements['ratio'],
    aq_keys['nitrogen_dioxide (μg/m³)']: measurements['ratio'],
    aq_keys['carbon_dioxide (ppm)']: measurements['ratio'],
    aq_keys['pm2_5 (μg/m³)']: measurements['ratio'],
    aq_keys['carbon_monoxide (μg/m³)']: measurements['ratio'],
    aq_keys['pm10 (μg/m³)']: measurements['ratio']
}

aq_descriptions = {
    aq_keys['time']: "Time of the measurement.",
    aq_keys['us_aqi (USAQI)']: "Air Quality Index is the overall standardized levels of health risk or air pollution.",
    aq_keys['us_aqi_pm2_5 (USAQI)']: "AQI for PM2.5 particles.",
    aq_keys['us_aqi_pm10 (USAQI)']: "AQI for PM10 particles.",
    aq_keys['us_aqi_nitrogen_dioxide (USAQI)']: "AQI for Nitrogen Dioxide.",
    aq_keys['us_aqi_carbon_monoxide (USAQI)']: "AQI for Carbon Monoxide.",
    aq_keys['us_aqi_ozone (USAQI)']: "AQI for Ozone.",
    aq_keys['us_aqi_sulphur_dioxide (USAQI)']: "AQI for Sulphur Dioxide.",
    aq_keys['methane (μg/m³)']: "A potent greenhouse gas that increases ozone levels.",
    aq_keys['uv_index_clear_sky ()']: "Measurement of the intensity of ultraviolet radiation from the sun under clear sky conditions, high levels can cause sunburn and skin cancer.",
    aq_keys['uv_index ()']: "Measurement of the intensity of ultraviolet radiation from the sun, high levels can cause sunburn and skin cancer.",
    aq_keys['dust (μg/m³)']: "Dust particles in the air that can cause coughing, wheezing, and asthma attacks.",
    aq_keys['aerosol_optical_depth ()']: "Measure of how much sunlight is blocked by airborne particles. High AOD indicates high concentration of particulate matters (PM2.5 and PM10).",
    aq_keys['ozone (μg/m³)']: "Created by chemical reactions between oxides of nitrogen and sunlight, it is a powerful lung irritant that can trigger asthma.",
    aq_keys['sulphur_dioxide (μg/m³)']: "Produced by burning fossil fuels, it constricts airways and is particularly dangerous for people with asthma.",
    aq_keys['nitrogen_dioxide (μg/m³)']: "Vehicle emissions can cause airway inflammation.",
    aq_keys['carbon_dioxide (ppm)']: "Colorless gas produced by burning fossil fuels. Not harmful outdoors.",
    aq_keys['pm2_5 (μg/m³)']: "Tiny particles that can lodge deep in the lungs and enter the bloodstream.",
    aq_keys['carbon_monoxide (μg/m³)']: "Odorless gas from combustion, reduces oxygen delivery to organs.",
    aq_keys['pm10 (μg/m³)']: "Includes dust, pollen, mold and affects the upper respiratory tract."
}

rv_measurements = {
    rv_keys['SEASON']: measurements['nominal'],
    rv_keys['AGE_GRP']: measurements['nominal'],
    rv_keys['RPHO_REGION']: measurements['nominal'],
    rv_keys['WEEKENDING']: measurements['interval'],
    rv_keys['MMWR_WEEK']: measurements['interval'],
    rv_keys['MMWR_YEAR']: measurements['interval'],
    rv_keys['COV_POSITIVES']: measurements['ratio'],
    rv_keys['COV_TOTAL_TESTS']: measurements['ratio'],
    rv_keys['COV_TP']: measurements['ratio'],
    rv_keys['COV_TP_LEVEL']: measurements['ordinal'],
    rv_keys['FLU_POSITIVES']: measurements['ratio'],
    rv_keys['FLU_TOTAL_TESTS']: measurements['ratio'],
    rv_keys['FLU_TP']: measurements['ratio'],
    rv_keys['FLU_TP_LEVEL']: measurements['ordinal'],
    rv_keys['RSV_POSITIVES']: measurements['ratio'],
    rv_keys['RSV_TOTAL_TESTS']: measurements['ratio'],
    rv_keys['RSV_TP']: measurements['ratio'],
    rv_keys['RSV_TP_LEVEL']: measurements['ordinal'],
    rv_keys['FLU_A_TESTS']: measurements['ratio'],
    rv_keys['FLU_B_TESTS']: measurements['ratio'],
    rv_keys['COV_ED_VISITS']: measurements['ratio'],
    rv_keys['FLU_ED_VISITS']: measurements['ratio'],
    rv_keys['RSV_ED_VISITS']: measurements['ratio'],
    rv_keys['POP']: measurements['ratio'],
    rv_keys['COV_ADM']: measurements['ratio'],
    rv_keys['FLU_ADM']: measurements['ratio'],
    rv_keys['RSV_ADM']: measurements['ratio'],
    rv_keys['COV_ADM_RATE']: measurements['ratio'],
    rv_keys['FLU_ADM_RATE']: measurements['ratio'],
    rv_keys['RSV_ADM_RATE']: measurements['ratio'],
    rv_keys['COV_ADM_LEVEL']: measurements['ordinal'],
    rv_keys['FLU_ADM_LEVEL']: measurements['ordinal'],
    rv_keys['RSV_ADM_LEVEL']: measurements['ordinal'],
    rv_keys['TOTAL_DEATHS']: measurements['ratio'],
    rv_keys['COV_DEATHS']: measurements['ratio'],
    rv_keys['FLU_DEATHS']: measurements['ratio'],
    rv_keys['RSV_DEATHS']: measurements['ratio'],
    rv_keys['COV_DEATHS_PER']: measurements['ratio'],
    rv_keys['FLU_DEATHS_PER']: measurements['ratio'],
    rv_keys['RSV_DEATHS_PER']: measurements['ratio'],
    rv_keys['SEASON_COV_PED_DEATHS']: measurements['ratio'],
    rv_keys['SEASON_FLU_PED_DEATHS']: measurements['ratio'],
    rv_keys['SEASON_RSV_PED_DEATHS']: measurements['ratio'],
}

rv_descriptions = {
    rv_keys['SEASON']: 'The annual surveillance cycle starting in summer (MMWR week 26).',
    rv_keys['AGE_GRP']: 'Demographic segments: 0-17 years, 18-64 years, and 65+ years.',
    rv_keys['RPHO_REGION']: 'The six California Regional Public Health Office areas or the whole state.',
    rv_keys['WEEKENDING']: 'The Saturday date marking the end of the CDC reporting week.',
    rv_keys['MMWR_WEEK']: 'Standardized CDC week number (1 to 52 or 53).',
    rv_keys['MMWR_YEAR']: 'The calendar year associated with the reporting week.',
    rv_keys['COV_POSITIVES']: 'Count of positive COVID-19 lab tests for the week.',
    rv_keys['COV_TOTAL_TESTS']: 'Total volume of COVID-19 lab tests performed.',
    rv_keys['COV_TP']: 'The percentage of COVID-19 tests that were positive. The formula is (COV_POSITIVES / COV_TOTAL_TESTS) * 100',
    rv_keys['COV_TP_LEVEL']: 'Positivity level based on 5 seasons of COVID-19 data.',
    rv_keys['FLU_POSITIVES']: 'Count of positive Influenza lab tests for the week.',
    rv_keys['FLU_TOTAL_TESTS']: 'Total volume of Influenza lab tests performed.',
    rv_keys['FLU_TP']: 'The percentage of Influenza tests that were positive. The formula is (FLU_POSITIVES / FLU_TOTAL_TESTS) * 100',
    rv_keys['FLU_TP_LEVEL']: 'Positivity level based on 5 seasons of Influenza data.',
    rv_keys['RSV_POSITIVES']: 'Count of positive RSV lab tests for the week.',
    rv_keys['RSV_TOTAL_TESTS']: 'Total volume of RSV lab tests performed.',
    rv_keys['RSV_TP']: 'The percentage of RSV tests that were positive. The formula is (RSV_POSITIVES / RSV_TOTAL_TESTS) * 100',
    rv_keys['RSV_TP_LEVEL']: 'Positivity level based on 5 seasons of RSV data.',
    rv_keys['FLU_A_TESTS']: 'Weekly count of positive tests for Influenza Type A.',
    rv_keys['FLU_B_TESTS']: 'Weekly count of positive tests for Influenza Type B.',
    rv_keys['COV_ED_VISITS']: 'Percentage of all ER visits related to COVID-19 symptoms.',
    rv_keys['FLU_ED_VISITS']: 'Percentage of all ER visits related to Influenza symptoms.',
    rv_keys['RSV_ED_VISITS']: 'Percentage of all ER visits related to RSV symptoms.',
    rv_keys['POP']: 'Regional population estimates used for rate calculations.',
    rv_keys['COV_ADM']: 'New weekly hospital admissions for COVID-19 (NHSN data).',
    rv_keys['FLU_ADM']: 'New weekly hospital admissions for Influenza (NHSN data).',
    rv_keys['RSV_ADM']: 'New weekly hospital admissions for RSV (NHSN data).',
    rv_keys['COV_ADM_RATE']: 'Weekly rate of COVID-19 admissions based on regional population.',
    rv_keys['FLU_ADM_RATE']: 'Weekly rate of Influenza admissions based on regional population.',
    rv_keys['RSV_ADM_RATE']: 'Weekly rate of RSV admissions based on regional population.',
    rv_keys['COV_ADM_LEVEL']: 'Admission level based on 5 seasons of COVID-19 positivity data.',
    rv_keys['FLU_ADM_LEVEL']: 'Admission level based on 5 seasons of Influenza positivity data.',
    rv_keys['RSV_ADM_LEVEL']: 'Admission level based on 5 seasons of RSV positivity data.',
    rv_keys['TOTAL_DEATHS']: 'Number of all-cause deaths each week.',
    rv_keys['COV_DEATHS']: 'Number of COVID-19 associated deaths each week.',
    rv_keys['FLU_DEATHS']: 'Number of influenza-associated deaths each week.',
    rv_keys['RSV_DEATHS']: 'Number of RSV-associated deaths each week.',
    rv_keys['COV_DEATHS_PER']: 'Percentage of all-cause deaths attributed to COVID-19.',
    rv_keys['FLU_DEATHS_PER']: 'Percentage of all-cause deaths attributed to Influenza.',
    rv_keys['RSV_DEATHS_PER']: 'Percentage of all-cause deaths attributed to RSV.',
    rv_keys['SEASON_COV_PED_DEATHS']: 'Number of COVID-19 associated pediatric deaths with lab-confirmation each week.',
    rv_keys['SEASON_FLU_PED_DEATHS']: 'Number of influenza-associated pediatric deaths with lab-confirmation each week.',
    rv_keys['SEASON_RSV_PED_DEATHS']: 'Number of RSV-associated pediatric deaths with lab-confirmation each week.',
}

stitched_measurements = {
    **{ key: aq_measurements[key] for key in keys.values() if key in aq_measurements},
    **{ key: rv_measurements[key] for key in keys.values() if key in rv_measurements},
}
stitched_descriptions = {
    **{ key: aq_descriptions[key] for key in keys.values() if key in aq_descriptions},
    **{ key: rv_descriptions[key] for key in keys.values() if key in rv_descriptions},
}
